// src/components/canvas/Cell.tsx
import type { ChangeEvent } from 'react';
import {
	Box,
	Button,
	Card,
	Flex,
	Separator,
	Text,
	TextField,
} from '@radix-ui/themes';

import { Link1Icon, LinkBreak1Icon } from '@radix-ui/react-icons';

import type { Values } from '../../project/types';

import { useOverride } from '../../project/slices/overrides';
import { useSettingsUnit } from '../../project/slices/settings';
import {
	disableOverride,
	enableOverride,
	updateOverride,
} from '../../project/slices/overrides';

import UnitField from '../ui/UnitField';

type EditProps = {
	id: string;
	rowIndex: number;
	columnIndex: number;
};

const Edit = ({ id, rowIndex, columnIndex }: EditProps) => {
	const override = useOverride(id, rowIndex, columnIndex);

	if (!override) {
		return;
	}

	const onChangeFontSize = (newValue: number) => {
		updateOverride(id, rowIndex, columnIndex, {
			fontSize: newValue,
		});
	};

	const onChangeLineHeight = (event: ChangeEvent<HTMLInputElement>) => {
		updateOverride(id, rowIndex, columnIndex, {
			lineHeight: parseFloat(event.target.value),
		});
	};

	const onClickLink = () => {
		disableOverride(id, rowIndex, columnIndex);
	};

	return (
		<Flex
			direction={'row'}
			gap="3"
			width={'100%'}
			align={'end'}
			justify={'between'}
		>
			<Flex
				direction={'row'}
				gap="3"
				width={'100%'}
				align={'end'}
				justify={'start'}
			>
				<UnitField
					id={`${rowIndex}:${columnIndex}-font-size`}
					label="Font Size"
					value={override.fontSize}
					onChange={onChangeFontSize}
				/>

				<Flex direction={'column'} align="start">
					<Text
						as="label"
						htmlFor={`${rowIndex}:${columnIndex}-line-height`}
					>
						Line Height
					</Text>
					<TextField.Root
						value={override.lineHeight}
						id={`${rowIndex}:${columnIndex}-line-height`}
						type="number"
						min={1}
						step={0.005}
						onChange={onChangeLineHeight}
					/>
				</Flex>
			</Flex>

			<Button onClick={onClickLink} variant="soft" color="gray">
				<Link1Icon /> Link
			</Button>
		</Flex>
	);
};

type DetailsProps = {
	values: Values;
	id: string;
	rowIndex: number;
	columnIndex: number;
};

const Details = ({ values, id, rowIndex, columnIndex }: DetailsProps) => {
	const unit = useSettingsUnit();

	const onClickUnlink = () => {
		enableOverride(id, rowIndex, columnIndex);
	};

	return (
		<Flex
			direction={'row'}
			width={'100%'}
			align={'end'}
			justify={'between'}
		>
			<Flex
				direction={'row'}
				width={'100%'}
				align={'end'}
				justify={'start'}
				gap={'6'}
			>
				<Flex direction={'column'} align="start">
					<Text size={'2'} as="p">
						Font Size
					</Text>
					<Text as="p" weight={'bold'}>
						{values.fontSize} {unit}
					</Text>
				</Flex>
				<Flex direction={'column'} align="start">
					<Text size={'2'} as="p">
						Line Height
					</Text>
					<Text as="p" weight={'bold'}>
						{values.lineHeight}
					</Text>
				</Flex>
			</Flex>

			<Button onClick={onClickUnlink} variant="soft" color="gray">
				<LinkBreak1Icon /> Unlink
			</Button>
		</Flex>
	);
};

type CellProps = {
	values: Values;
	id: string;
	rowIndex: number;
	columnIndex: number;
};

const Cell = ({ values, id, rowIndex, columnIndex }: CellProps) => {
	const unit = useSettingsUnit();
	const override = useOverride(id, rowIndex, columnIndex);

	return (
		<Box width={'500px'}>
			<Card>
				<Flex gap={'2'} align={'start'} direction={'column'}>
					<p
						style={{
							fontFamily: values.fontFamily,
							fontStyle: values.fontStyle,
							fontWeight: values.fontWeight,
							fontSize: `${values.fontSize}${unit}`,
							lineHeight: values.lineHeight,
							margin: '0',
							whiteSpace: 'nowrap',
							width: '100%',
							overflow: 'hidden',
						}}
					>
						Lorem ipsum dolor sit amet consectetur adipisicing elit.
					</p>

					<Separator size={'4'} orientation={'horizontal'} />

					{override === undefined ? (
						<Details
							values={values}
							id={id}
							rowIndex={rowIndex}
							columnIndex={columnIndex}
						/>
					) : (
						<Edit
							id={id}
							rowIndex={rowIndex}
							columnIndex={columnIndex}
						/>
					)}
				</Flex>
			</Card>
		</Box>
	);
};

export default Cell;

// src/routes/editor/[id]/_components/Cell.svelte
<script lang="ts">
	import type { GridCell } from '$lib/types';

	import settings from '$lib/stores/settings.svelte';

	import Separator from '$lib/ui/display/separator.svelte';
	import Input from '$lib/ui/form/input.svelte';
	import InputUnit from '$lib/ui/form/input-unit.svelte';
	import project from '$lib/stores/project.svelte';
	import Button from '$lib/ui/button/button.svelte';

	type CellProps = {
		breakpointId: string;
		cell: GridCell;
	};

	let { breakpointId, cell }: CellProps = $props();
</script>

<li class="col-span-1 border border-black">
	<div class="block overflow-hidden border-b border-black p-4">
		<p
			style:line-height={cell.lineHeight}
			style:font-family={cell.family}
			style:font-size={`${cell.fontSize.toFixed(3)}${settings.unit}`}
			style:font-weight={cell.weight}
			style:font-style={cell.style}
		>
			Lorem ipsum dolor sit amet consectetur adipisicing elit.
		</p>
	</div>

	<ul class="grid grid-cols-3 gap-4 p-4">
		<li>
			<Separator
				as="label"
				for={`input-line-height-${cell.id}`}
				description={cell.lineHeightOverridden ? 'Unlinked' : ''}
				>Line Height
			</Separator>
			<Input
				id={`input-line-height-${cell.id}`}
				class="mt-1"
				type="number"
				min={0}
				step={0.05}
				value={cell.lineHeight}
				oninput={(event) =>
					project.updateBreakpointOverrideValue(
						breakpointId,
						cell.id,
						'lineHeight',
						Number(event.currentTarget.value)
					)}
			/>

			{#if cell.lineHeightOverridden}
				<Button
					label="Relink"
					class="mt-4"
					onclick={() =>
						project.updateBreakpointOverrideValue(
							breakpointId,
							cell.id,
							'lineHeight',
							undefined
						)}
				/>
			{/if}
		</li>
		<li>
			<Separator
				as="label"
				for={`input-font-size-${cell.id}`}
				description={cell.fontSizeOverridden ? 'Unlinked' : ''}
				>Font Size
			</Separator>
			<InputUnit
				id={`input-font-size-${cell.id}`}
				value={cell.fontSize}
				min={0}
				step={0.05}
				unit={settings.unit}
				oninput={(event) =>
					project.updateBreakpointOverrideValue(
						breakpointId,
						cell.id,
						'fontSize',
						Number(event.currentTarget.value)
					)}
			/>

			{#if cell.fontSizeOverridden}
				<Button
					label="Relink"
					class="mt-4"
					onclick={() =>
						project.updateBreakpointOverrideValue(
							breakpointId,
							cell.id,
							'fontSize',
							undefined
						)}
				/>
			{/if}
		</li>
	</ul>
</li>
